Remove obsolete params (#37)
Fixes:

Error: obsolete parameter MaxLineLength (for Style/IfUnlessModifier) found in .rubocop-https---raw-githubusercontent-com-MarsBased-marstyle-master-ruby--rubocop-yml
Style/IfUnlessModifier: MaxLineLength has been removed. Use Metrics/LineLength: Max instead
obsolete parameter MaxLineLength (for Style/WhileUntilModifier) found in .rubocop-https---raw-githubusercontent-com-MarsBased-marstyle-master-ruby--rubocop-yml
Style/WhileUntilModifier: MaxLineLength has been removed. Use Metrics/LineLength: Max instead